name:                Digital-Orrey
version:             0.1.0.0
github:              "githubuser/Digital-Orrey"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- DeriveGeneric
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Digital-Orrey#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Digital-Orrey-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Digital-Orrey



tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - hspec
    - QuickCheck

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - hspec
    - QuickCheck

tests:
  Digital-Orrey-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Digital-Orrey
